### ISSUE TITLE
Materials on custom collections

### ISSUE THREAD

**Issue by zzhengnan** [jrbourbeau/hacking-dask#19]
@jrbourbeau Thanks for these great tutorials! I'm wondering if you have additional materials on creating _custom collections_ beyond the example in the documentation https://docs.dask.org/en/latest/custom-collections.html#example-dask-collection.

I've inherited a codebase that relies heavily on a custom collection (written by one of Dask's core developers actually) and would love to learn more about its inner workings. 

Custom collections are briefly teased at the end of `3-graph-optimization.ipynb` but ultimately aren't covered in the next notebook.

> There are some great [optimization techniques] included by default (cull, inline, fuse), but sometimes it can be really powerful to write custom optimizations and either use them on existing collections or on custom collections. We'll touch on this a bit more in the next section about custom collections.

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @zzhengnan! For a previous version of this tutorial @jsignell put together a [notebook on custom collections](https://github.com/jrbourbeau/hacking-dask/blob/9e864dd322b4a950b97162916faba59873da5618/4-custom-collections.ipynb). You may find that useful. That said, I think most of the material which is presented in that notebook is also covered in the docs at https://docs.dask.org/en/latest/custom-collections.html. 

Is there something in particular you think is missing from https://docs.dask.org/en/latest/custom-collections.html?

**Comment by zzhengnan** [comment]
Thanks for the reply, James. I'll study the notebook in more detail this weekend to see if it helps deepen my understanding of custom collections.

I don't think I understand this topic well enough to opine on what's potentially missing from the official docs. Will certainly report back once I do. Until then, mind if we keep this issue open?

**Comment by jrbourbeau** [comment]
Yeah, no worries

**Comment by zzhengnan** [comment]
I haven't dug into this as deep as I would've liked. Closing the issue for now. Will reopen later if necessary.
